version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12.x
    commands:
  pre_build:
    commands:
      - echo Installing dependencies...
      - npm install --force
      - npm install -g @angular/cli
  build:
    commands:
      - echo Build started on `date`
      - ng build --configuration ${ENVIRONMENT}
      - echo Build completed on `date`
      - aws s3 sync --delete ./dist s3://${FRONTEND_S3}/
      - aws cloudfront create-invalidation --distribution-id ${CLOUDFRONT_DISTRIBUTION_ID} --paths "/*"
  post_build:
    commands:
