export const environment = {
  env: '',
  api_url: '',
  aws_cognito_region: '',
  aws_user_pools_id: '',
  aws_user_pools_web_client_id: '',
  aws_user_pools_id_admin: '',
  aws_user_pools_web_client_id_admin: '',
  frontend_url: '',
  omron_connect_registration_link: '',
  omron_connect_purchase_link: '',
  omron_connect_group_id: '',
  omron_connect_app_id: '',
  amchart_license_code: '',
  firebase_key_pair: '',
  firebase_server_key: '',
  firebase_api_key: '',
  firebase_auth_domain: '',
  firebase_project_id: '',
  firebase_storage_bucket: '',
  firebase_messaging_sender_id: '',
  firebase_app_id: '',
};
